config/routes.rb
HowTo::Application.routes.draw do

  resources :guides do
    resources :steps
  end

  root 'guides#index'

end

app/models/guide.rb
class Guide < ActiveRecord::Base
  validates :guide_for,  :presence => true
  validates :guide_name, :presence => true, :length => { :minimum => 4 }

  has_many :steps
end

app/models/step.rb
class Step < ActiveRecord::Base
  validates :step_number,  :presence => true
  validates :step_name, :presence => true, :length => { :minimum => 4 }
  validates :content, :presence => true

  belongs_to :guide
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/guides_controller.rb
class GuidesController < ApplicationController
  before_action :set_guide, only: [:show, :edit, :update, :destroy]

  # GET /guides
  # GET /guides.json
  def index
    @guides = Guide.all
  end

  # GET /guides/1
  # GET /guides/1.json
  def show
  end

  # GET /guides/new
  def new
    @guide = Guide.new
  end

  # GET /guides/1/edit
  def edit
  end

  # POST /guides
  # POST /guides.json
  def create
    @guide = Guide.new(guide_params)

    respond_to do |format|
      if @guide.save
        format.html { redirect_to @guide, notice: 'Guide was successfully created.' }
        format.json { render action: 'show', status: :created, location: @guide }
      else
        format.html { render action: 'new' }
        format.json { render json: @guide.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /guides/1
  # PATCH/PUT /guides/1.json
  def update
    respond_to do |format|
      if @guide.update(guide_params)
        format.html { redirect_to @guide, notice: 'Guide was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @guide.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /guides/1
  # DELETE /guides/1.json
  def destroy
    @guide.destroy
    respond_to do |format|
      format.html { redirect_to guides_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_guide
      @guide = Guide.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def guide_params
      params.require(:guide).permit(:guide_for, :guide_name, :info)
    end
end

app/controllers/steps_controller.rb
class StepsController < ApplicationController
  before_action :set_step, only: [:show, :edit, :update, :destroy]
  before_action :guide

  def index
    @steps = guide.steps
    @id = guide.id
  end

  def show
    @step = guide.steps.find(params[:id])
  end

  def new
    @step = guide.steps.build
  end

  def edit
    @step = guide.steps.find(params[:id])
  end

  def create
    @step = guide.steps.build(step_params)

    respond_to do |format|
      if @step.save
        format.html { redirect_to([@step.guide, @step], notice: 'Step was successfully created.') }
        format.json { render action: 'show', status: :created, location: [@step.guide, @step] }
      else
        format.html { render action: 'new' }
        format.json { render json: @step.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @step = guide.steps.find(step_params)

    respond_to do |format|
      if @step.update(step_params)
        format.html { redirect_to [@step.guide, @step], notice: 'Step was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @step.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @step = guide.steps.find(params[:step])

    @step.destroy
    respond_to do |format|
      format.html { redirect_to guide_steps_url }
      format.json { head :no_content }
    end
  end

  private
    def guide
      Guide.find(params[:guide_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def step_params
      params.require(:step).permit(:step_number, :step_name, :content)
    end

    def set_step
      @step = Step.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/guides_helper.rb
module GuidesHelper
end

app/helpers/steps_helper.rb
module StepsHelper
end

app/views/guides/_form.html.erb
<%= form_for(@guide) do |f| %>
  <% if @guide.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@guide.errors.count, "error") %> prohibited this guide from being saved:</h2>

      <ul>
      <% @guide.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :guide_for %><br>
    <%= f.text_field :guide_for %>
  </div>
  <div class="field">
    <%= f.label :guide_name %><br>
    <%= f.text_field :guide_name %>
  </div>
  <div class="field">
    <%= f.label :info %><br>
    <%= f.text_area :info %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/guides/edit.html.erb
<h1>Editing guide</h1>

<%= render 'form' %>

<%= link_to 'Show', @guide %> |
<%= link_to 'Back', guides_path %>

app/views/guides/index.html.erb
<h1>Listing guides</h1>

<table>
  <thead>
    <tr>
      <th>Guide for</th>
      <th>Guide name</th>
      <th>Info</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @guides.each do |guide| %>
      <tr>
        <td><%= guide.guide_for %></td>
        <td><%= guide.guide_name %></td>
        <td><%= guide.info %></td>
        <td><%= link_to 'Show', guide %></td>
        <td><%= link_to 'Edit', edit_guide_path(guide) %></td>
        <td><%= link_to 'Destroy', guide, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Guide', new_guide_path %>

app/views/guides/new.html.erb
<h1>New guide</h1>

<%= render 'form' %>

<%= link_to 'Back', guides_path %>

app/views/guides/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Guide for:</strong>
  <%= @guide.guide_for %>
</p>

<p>
  <strong>Guide name:</strong>
  <%= @guide.guide_name %>
</p>

<p>
  <strong>Info:</strong>
  <%= @guide.info %>
</p>

<%= link_to 'Steps', guide_steps_path(@guide) %>
<%= link_to 'Edit', edit_guide_path(@guide) %> |
<%= link_to 'Back', guides_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HowTo</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/steps/_form.html.erb
# <%= form_for([@step.guide, @step]) do |f| %>
  <% if @step.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@step.errors.count, "error") %> prohibited this step from being saved:</h2>

      <ul>
      <% @step.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :step_number %><br>
    <%= f.number_field :step_number %>
  </div>
  <div class="field">
    <%= f.label :step_name %><br>
    <%= f.text_field :step_name %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/steps/edit.html.erb
<h1>Editing step</h1>

<%= render 'form' %>

<%= link_to 'Show', [@step.guide, @step] %> |
<%= link_to 'Back', guide_steps_path(@step.guide) %>

app/views/steps/index.html.erb
<h1>Listing steps</h1>

<table>
  <thead>
    <tr>
      <th>Step number</th>
      <th>Step name</th>
      <th>Content</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @steps.each do |step| %>
      <tr>
        <td><%= step.step_number %></td>
        <td><%= step.step_name %></td>
        <td><%= step.content %></td>
        <td><%= link_to 'Show', [step.guide, step] %></td>
        <td><%= link_to 'Edit', edit_guide_step_path(step.guide, step) %></td>
        <td><%= link_to 'Destroy', [step.guide, step], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Guide', guide_path(@id) %>
<%= link_to 'New Step', new_guide_step_path %>

app/views/steps/new.html.erb
<h1>New step</h1>

<%= render 'form' %>

<%= link_to 'Back', guide_steps_path(@step.guide) %>

app/views/steps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Step number:</strong>
  <%= @step.step_number %>
</p>

<p>
  <strong>Step name:</strong>
  <%= @step.step_name %>
</p>

<p>
  <strong>Content:</strong>
  <%= @step.content %>
</p>

<%= link_to 'New', new_guide_step_path( @step.guide )  %>
<%= link_to 'Edit', edit_guide_step_path(@step.guide, @step) %> |
<%= link_to 'Back', guide_steps_path(@step.guide) %>